// Define types for the elements we'll display in the periodic table
export interface Element {
  atomicNumber: number;
  atomicWeight: number;
  chemicalGroup: string;
  isShaking: boolean;
  reactants: boolean;
  symbol: string;
  name: string;
}

export const elementsNoActinidesOrLanthanides: Element[] = [
  // Row 1
  {
    symbol: "H",
    name: "Hydrogen",
    atomicNumber: 1,
    atomicWeight: 1.008,
    chemicalGroup: "nonmetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "He",
    name: "Helium",
    atomicNumber: 2,
    atomicWeight: 4.0026,
    chemicalGroup: "nobleGas",
    isShaking: false,
    reactants: false,
  },

  // Row 2
  {
    symbol: "Li",
    name: "Lithium",
    atomicNumber: 3,
    atomicWeight: 6.94,
    chemicalGroup: "alkaliMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Be",
    name: "Beryillum",
    atomicNumber: 4,
    atomicWeight: 9.1022,
    chemicalGroup: "alkalineEarthMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "B",
    name: "Boron",
    atomicNumber: 5,
    atomicWeight: 10.81,
    chemicalGroup: "metalloid",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "C",
    name: "Carbon",
    atomicNumber: 6,
    atomicWeight: 12.01,
    chemicalGroup: "nonmetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "N",
    name: "Nitrogen",
    atomicNumber: 7,
    atomicWeight: 14.007,
    chemicalGroup: "nonmetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "O",
    name: "Oxygen",
    atomicNumber: 8,
    atomicWeight: 16.0,
    chemicalGroup: "nonmetal",
    isShaking: true,
    reactants: true,
  },
  {
    symbol: "F",
    name: "Fluorine",
    atomicNumber: 9,
    atomicWeight: 18.998,
    chemicalGroup: "halogen",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ne",
    name: "Neon",
    atomicNumber: 10,
    atomicWeight: 20.18,
    chemicalGroup: "nobleGas",
    isShaking: false,
    reactants: false,
  },

  // Row 3
  {
    symbol: "Na",
    name: "Sodium",
    atomicNumber: 11,
    atomicWeight: 22.99,
    chemicalGroup: "alkaliMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Mg",
    name: "Magnesium",
    atomicNumber: 12,
    atomicWeight: 24.305,
    chemicalGroup: "alkalineEarthMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "H",
    name: "placeholder",
    atomicNumber: 1,
    chemicalGroup: "hydrogen",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Al",
    name: "Aluminum",
    atomicNumber: 13,
    atomicWeight: 26.982,
    chemicalGroup: "postTransitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Si",
    name: "Silicon",
    atomicNumber: 14,
    atomicWeight: 28.085,
    chemicalGroup: "metalloid",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "P",
    name: "Phosphorus",
    atomicNumber: 15,
    atomicWeight: 30.974,
    chemicalGroup: "nonmetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "S",
    name: "Sulfur",
    atomicNumber: 16,
    atomicWeight: 32.06,
    chemicalGroup: "nonmetal",
    isShaking: true,
    reactants: true,
  },
  {
    symbol: "Cl",
    name: "Chlorine",
    atomicNumber: 17,
    atomicWeight: 35.45,
    chemicalGroup: "halogen",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ar",
    name: "Argon",
    atomicNumber: 18,
    atomicWeight: 39.948,
    chemicalGroup: "nobleGas",
    isShaking: false,
    reactants: false,
  },

  // Row 4
  {
    symbol: "K",
    name: "Potassium",
    atomicNumber: 19,
    atomicWeight: 39.098,
    chemicalGroup: "alkaliMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ca",
    name: "Calcium",
    atomicNumber: 20,
    atomicWeight: 40.078,
    chemicalGroup: "alkalineEarthMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Sc",
    name: "Scandium",
    atomicNumber: 21,
    atomicWeight: 44.956,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ti",
    name: "Titanium",
    atomicNumber: 22,
    atomicWeight: 47.867,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "V",
    name: "Vanadium",
    atomicNumber: 23,
    atomicWeight: 50.942,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Cr",
    name: "Chromium",
    atomicNumber: 24,
    atomicWeight: 51.996,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Mn",
    name: "Manganese",
    atomicNumber: 25,
    atomicWeight: 54.938,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Fe",
    name: "Iron",
    atomicNumber: 26,
    atomicWeight: 55.845,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Co",
    name: "Cobalt",
    atomicNumber: 27,
    atomicWeight: 58.933,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ni",
    name: "Nickel",
    atomicNumber: 28,
    atomicWeight: 58.693,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Cu",
    name: "Copper",
    atomicNumber: 29,
    atomicWeight: 63.546,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Zn",
    name: "Zinc",
    atomicNumber: 30,
    atomicWeight: 65.38,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ga",
    name: "Gallium",
    atomicNumber: 31,
    atomicWeight: 69.723,
    chemicalGroup: "postTransitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ge",
    name: "Germanium",
    atomicNumber: 32,
    atomicWeight: 72.63,
    chemicalGroup: "metalloid",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "As",
    name: "Arsenic",
    atomicNumber: 33,
    atomicWeight: 74.922,
    chemicalGroup: "metalloid",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Se",
    name: "Selenium",
    atomicNumber: 34,
    atomicWeight: 78.971,
    chemicalGroup: "nonmetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Br",
    name: "Bromine",
    atomicNumber: 35,
    atomicWeight: 79.904,
    chemicalGroup: "halogen",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Kr",
    name: "Krypton",
    atomicNumber: 36,
    atomicWeight: 83.798,
    chemicalGroup: "nobleGas",
    isShaking: false,
    reactants: false,
  },

  // Row 5
  {
    symbol: "Rb",
    name: "Rubidium",
    atomicNumber: 37,
    atomicWeight: 85.468,
    chemicalGroup: "alkaliMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Sr",
    name: "Strontium",
    atomicNumber: 38,
    atomicWeight: 87.62,
    chemicalGroup: "alkalineEarthMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Y",
    name: "Yttrium",
    atomicNumber: 39,
    atomicWeight: 88.906,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Zr",
    name: "Zirconium",
    atomicNumber: 40,
    atomicWeight: 91.224,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Nb",
    name: "Niobium",
    atomicNumber: 41,
    atomicWeight: 92.906,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Mo",
    name: "Molybdenum",
    atomicNumber: 42,
    atomicWeight: 95.95,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Tc",
    name: "Technetium",
    atomicNumber: 43,
    atomicWeight: 98,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ru",
    name: "Ruthenium",
    atomicNumber: 44,
    atomicWeight: 101.07,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Rh",
    name: "Rhodium",
    atomicNumber: 45,
    atomicWeight: 102.91,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Pd",
    name: "Palladium",
    atomicNumber: 46,
    atomicWeight: 106.42,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ag",
    name: "Silver",
    atomicNumber: 47,
    atomicWeight: 107.87,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Cd",
    name: "Cadmium",
    atomicNumber: 48,
    atomicWeight: 112.41,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "In",
    name: "Indium",
    atomicNumber: 49,
    atomicWeight: 114.82,
    chemicalGroup: "postTransitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Sn",
    name: "Tin",
    atomicNumber: 50,
    atomicWeight: 118.71,
    chemicalGroup: "postTransitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Sb",
    name: "Antimony",
    atomicNumber: 51,
    atomicWeight: 121.76,
    chemicalGroup: "metalloid",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Te",
    name: "Tellurium",
    atomicNumber: 52,
    atomicWeight: 127.6,
    chemicalGroup: "metalloid",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "I",
    name: "Iodine",
    atomicNumber: 53,
    atomicWeight: 126.905,
    chemicalGroup: "halogen",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Xe",
    name: "Xenon",
    atomicNumber: 54,
    atomicWeight: 131.29,
    chemicalGroup: "nobleGas",
    isShaking: false,
    reactants: false,
  },

  // Row 6
  {
    symbol: "Cs",
    name: "Cesium",
    atomicNumber: 55,
    atomicWeight: 132.91,
    chemicalGroup: "alkaliMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ba",
    name: "Barium",
    atomicNumber: 56,
    atomicWeight: 137.33,
    chemicalGroup: "alkalineEarthMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "57-71",
    name: "Lanthanides",
    atomicNumber: 1,
    chemicalGroup: "lanthanides",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Hf",
    name: "Hafnium",
    atomicNumber: 72,
    atomicWeight: 178.49,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ta",
    name: "Tantalum",
    atomicNumber: 73,
    atomicWeight: 180.95,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "W",
    name: "Tungsten",
    atomicNumber: 74,
    atomicWeight: 183.84,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Re",
    name: "Rhenium",
    atomicNumber: 75,
    atomicWeight: 186.21,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Os",
    name: "Osmium",
    atomicNumber: 76,
    atomicWeight: 190.23,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ir",
    name: "Iridium",
    atomicNumber: 77,
    atomicWeight: 192.22,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Pt",
    name: "Platinum",
    atomicNumber: 78,
    atomicWeight: 195.08,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Au",
    name: "Gold",
    atomicNumber: 79,
    atomicWeight: 196.97,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Hg",
    name: "Mercury",
    atomicNumber: 80,
    atomicWeight: 200.59,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Tl",
    name: "Thallium",
    atomicNumber: 81,
    atomicWeight: 204.38,
    chemicalGroup: "postTransitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Pb",
    name: "Lead",
    atomicNumber: 82,
    atomicWeight: 207.2,
    chemicalGroup: "postTransitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Bi",
    name: "Bismuth",
    atomicNumber: 83,
    atomicWeight: 208.98,
    chemicalGroup: "postTransitionMetal",
    isShaking: true,
    reactants: true,
  },
  {
    symbol: "Po",
    name: "Polonium",
    atomicNumber: 84,
    atomicWeight: 209,
    chemicalGroup: "metalloid",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "At",
    name: "Astatine",
    atomicNumber: 85,
    atomicWeight: 210,
    chemicalGroup: "halogen",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Rn",
    name: "Radon",
    atomicNumber: 86,
    atomicWeight: 222,
    chemicalGroup: "nobleGas",
    isShaking: false,
    reactants: false,
  },

  // Row 7
  {
    symbol: "Fr",
    name: "Francium",
    atomicNumber: 87,
    atomicWeight: 223,
    chemicalGroup: "alkaliMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ra",
    name: "Radium",
    atomicNumber: 88,
    atomicWeight: 226,
    chemicalGroup: "alkalineEarthMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "89-103",
    name: "Actinides",
    atomicNumber: 1,
    chemicalGroup: "actinides",
    atomicWeight: 1,
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Rf",
    name: "Rutherfordium",
    atomicNumber: 104,
    atomicWeight: 267,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Db",
    name: "Dubnium",
    atomicNumber: 105,
    atomicWeight: 270,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Sg",
    name: "Seaborgium",
    atomicNumber: 106,
    atomicWeight: 271,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Bh",
    name: "Bohrium",
    atomicNumber: 107,
    atomicWeight: 270,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Hs",
    name: "Hassium",
    atomicNumber: 108,
    atomicWeight: 277,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Mt",
    name: "Meitnerium",
    atomicNumber: 109,
    atomicWeight: 278,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ds",
    name: "Darmstadtium",
    atomicNumber: 110,
    atomicWeight: 281,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Rg",
    name: "Roentgenium",
    atomicNumber: 111,
    atomicWeight: 282,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Cn",
    name: "Copernicium",
    atomicNumber: 112,
    atomicWeight: 285,
    chemicalGroup: "transitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Nh",
    name: "Nihonium",
    atomicNumber: 113,
    atomicWeight: 286,
    chemicalGroup: "postTransitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Fl",
    name: "Flerovium",
    atomicNumber: 114,
    atomicWeight: 289,
    chemicalGroup: "postTransitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Mc",
    name: "Moscovium",
    atomicNumber: 115,
    atomicWeight: 290,
    chemicalGroup: "postTransitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Lv",
    name: "Livermorium",
    atomicNumber: 116,
    atomicWeight: 293,
    chemicalGroup: "postTransitionMetal",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ts",
    name: "Tennessine",
    atomicNumber: 117,
    atomicWeight: 294,
    chemicalGroup: "halogen",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Og",
    name: "Oganesson",
    atomicNumber: 118,
    atomicWeight: 294,
    chemicalGroup: "nobleGas",
    isShaking: false,
    reactants: false,
  },
];

export const lanthanidesAndActinides = [
  // lanthanides
  {
    symbol: "La",
    name: "Lanthanum",
    atomicNumber: 57,
    atomicWeight: 138.91,
    chemicalGroup: "lanthanides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ce",
    name: "Cerium",
    atomicNumber: 58,
    atomicWeight: 140.12,
    chemicalGroup: "lanthanides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Pr",
    name: "Praseody.",
    atomicNumber: 59,
    atomicWeight: 140.91,
    chemicalGroup: "lanthanides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Nd",
    name: "Neodymium",
    atomicNumber: 60,
    atomicWeight: 144.24,
    chemicalGroup: "lanthanides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Pm",
    name: "Promethium",
    atomicNumber: 61,
    atomicWeight: 145,
    chemicalGroup: "lanthanides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Sm",
    name: "Samarium",
    atomicNumber: 62,
    atomicWeight: 150.36,
    chemicalGroup: "lanthanides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Eu",
    name: "Europium",
    atomicNumber: 63,
    atomicWeight: 151.96,
    chemicalGroup: "lanthanides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Gd",
    name: "Gadolinium",
    atomicNumber: 64,
    atomicWeight: 157.25,
    chemicalGroup: "lanthanides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Tb",
    name: "Terbium",
    atomicNumber: 65,
    atomicWeight: 158.93,
    chemicalGroup: "lanthanides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Dy",
    name: "Dysprosium",
    atomicNumber: 66,
    atomicWeight: 162.5,
    chemicalGroup: "lanthanides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Ho",
    name: "Holmium",
    atomicNumber: 67,
    atomicWeight: 164.93,
    chemicalGroup: "lanthanides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Er",
    name: "Erbium",
    atomicNumber: 68,
    atomicWeight: 167.26,
    chemicalGroup: "lanthanides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Tm",
    name: "Thulium",
    atomicNumber: 69,
    atomicWeight: 168.93,
    chemicalGroup: "lanthanides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Yb",
    name: "Ytterbium",
    atomicNumber: 70,
    atomicWeight: 173.05,
    chemicalGroup: "lanthanides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Lu",
    name: "Lutetium",
    atomicNumber: 71,
    atomicWeight: 174.97,
    chemicalGroup: "lanthanides",
    isShaking: false,
    reactants: false,
  },

  // actinides
  {
    symbol: "Ac",
    name: "Actinium",
    atomicNumber: 89,
    atomicWeight: 227,
    chemicalGroup: "actinides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Th",
    name: "Thorium",
    atomicNumber: 90,
    atomicWeight: 232.04,
    chemicalGroup: "actinides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Pa",
    name: "Protactinium",
    atomicNumber: 91,
    atomicWeight: 231.04,
    chemicalGroup: "actinides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "U",
    name: "Uranium",
    atomicNumber: 92,
    atomicWeight: 238.03,
    chemicalGroup: "actinides",
    isShaking: true,
    reactants: true,
  },
  {
    symbol: "Np",
    name: "Neptunium",
    atomicNumber: 93,
    atomicWeight: 237,
    chemicalGroup: "actinides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Pu",
    name: "Plutonium",
    atomicNumber: 94,
    atomicWeight: 244,
    chemicalGroup: "actinides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Am",
    name: "Americium",
    atomicNumber: 95,
    atomicWeight: 243,
    chemicalGroup: "actinides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Cm",
    name: "Curium",
    atomicNumber: 96,
    atomicWeight: 247,
    chemicalGroup: "actinides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Bk",
    name: "Berkelium",
    atomicNumber: 97,
    atomicWeight: 247,
    chemicalGroup: "actinides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Cf",
    name: "Californium",
    atomicNumber: 98,
    atomicWeight: 251,
    chemicalGroup: "actinides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Es",
    name: "Einsteinium",
    atomicNumber: 99,
    atomicWeight: 252,
    chemicalGroup: "actinides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Fm",
    name: "Fermium",
    atomicNumber: 100,
    atomicWeight: 257,
    chemicalGroup: "actinides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Md",
    name: "Mendelevium",
    atomicNumber: 101,
    atomicWeight: 258,
    chemicalGroup: "actinides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "No",
    name: "Nobelium",
    atomicNumber: 102,
    atomicWeight: 259,
    chemicalGroup: "actinides",
    isShaking: false,
    reactants: false,
  },
  {
    symbol: "Lr",
    name: "Lawrencium",
    atomicNumber: 103,
    atomicWeight: 266,
    chemicalGroup: "actinides",
    isShaking: false,
    reactants: false,
  },
];
